version: '3.1'

services:

  mysql8017:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/fredy/dockerVolumes/mysql8017:/var/lib/mysql